sources:
  - name: mfuu-FreeProxies
    url: https://raw.githubusercontent.com/mfuu/FreeProxies/master/sub.yaml
  - name: vxiaov-free-proxies
    url: https://raw.githubusercontent.com/vxiaov/free_proxies/main/clash/clash.provider.yaml
