mixed-port: 7890
external-controller: 127.0.0.1:9090
allow-lan: false
mode: rule
log-level: warning
ipv6: false
unified-delay: true
proxy-groups:
  - name: FREE_NODE_POOL
    type: url-test
    url: https://www.google.com/generate_204
    interval: 300
    lazy: false
    timeout: 8000
    expected-status: 204
    proxies: []
rules:
  - MATCH,FREE_NODE_POOL
